# 인코딩의 문제등의 불편함으로 인해 기존의aplication.properties파일이 아닌 yml 파일을 설정
#server port config
server:
  port: 8585
  
# oracle driver config
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@125.132.252.115:1521:xe
    username: C##JANDI
    password: JANDI
 #이메일 설정    
  mail: 
    host: smtp.gmail.com
    port: 587
    username: tnsvy2004@gmail.com
    password: gsp0221!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # 정적소스(html, js, css) 변경 바로 적용하기
  devtools: 
    livereload:
      enabled: true
  freemarker:
    cache: false
  
  # thymeleaf 설정
  thymeleaf: 
    prefix: classpath:/templates/
    cache: false
    
# mybatis config (mappers/**/*.xml -> 매퍼스 밑에 모든 이름의 xml을 사용)
mybatis:
  mapper-locations: mappers/**/*.xml
  # type-alias 설정
  type-aliases-package: com.jandiFactoring.redJandi.**.*.dto
 

 
  